import { StyleSheet, Platform, StatusBar, Dimensions } from "react-native";

export const requiredFields = [
  "first_name",
  "last_name",
  "birthday",
  "street",
  "brgy",
  "city",
  "child_name",
  "child_bday",
  "birth_weight",
  "aog",
  "contact_number",
  "email",
];

export const BARANGAY_OPTIONS = [
  { label: "Bagumbayan", value: "Bagumbayan" },
  { label: "Bambang", value: "Bambang" },
  { label: "Calzada", value: "Calzada" },
  { label: "Cembo", value: "Cembo" },
  { label: "Central Bicutan", value: "Central Bicutan" },
  { label: "Central Signal Village", value: "Central Signal Village" },
  { label: "Comembo", value: "Comembo" },
  { label: "East Rembo", value: "East Rembo" },
  { label: "Fort Bonifacio", value: "Fort Bonifacio" },
  { label: "Hagonoy", value: "Hagonoy" },
  { label: "Ibayo Tipas", value: "Ibayo Tipas" },
  { label: "Katuparan", value: "Katuparan" },
  { label: "Ligid Tipas", value: "Ligid Tipas" },
  { label: "Lower Bicutan", value: "Lower Bicutan" },
  { label: "Maharlika Village", value: "Maharlika Village" },
  { label: "Napindan", value: "Napindan" },
  { label: "New Lower Bicutan", value: "New Lower Bicutan" },
  { label: "North Daang Hari", value: "North Daang Hari" },
  { label: "North Signal Village", value: "North Signal Village" },
  { label: "Northside", value: "Northside" },
  { label: "Palingon", value: "Palingon" },
  { label: "Pembo", value: "Pembo" },
  { label: "Pinagsama", value: "Pinagsama" },
  { label: "Pitogo", value: "Pitogo" },
  { label: "Rizal", value: "Rizal" },
  { label: "San Miguel", value: "San Miguel" },
  { label: "Santa Ana", value: "Santa Ana" },
  { label: "South Daang Hari", value: "South Daang Hari" },
  { label: "South Signal Village", value: "South Signal Village" },
  { label: "Tanyag", value: "Tanyag" },
  { label: "Tuktukan", value: "Tuktukan" },
  { label: "Upper Bicutan", value: "Upper Bicutan" },
  { label: "Ususan", value: "Ususan" },
  { label: "Wawa", value: "Wawa" },
  { label: "West Rembo", value: "West Rembo" },
  { label: "Western Bicutan", value: "Western Bicutan" },
  { label: "Other", value: "Other" },
];

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: "#f5f5f5",
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  section: {
    marginBottom: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    backgroundColor: "#f9f9f9",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
  },
  input: {
    height: 40,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 4,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  navButtons: {
    flex: 1,
    justifyContent: "center", // Center buttons vertically
    alignItems: "center", // Align buttons horizontally
    paddingHorizontal: 16,
  },
  button: {
    backgroundColor: "#E53777",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    width: "80%",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  datePickerButton: {
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0e0e0",
    borderRadius: 4,
    marginBottom: 16,
  },
  datePickerText: {
    color: "#000",
  },
  itemContainer: {
    marginBottom: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    backgroundColor: "#ffffff",
  },
  bagsList: {
    marginTop: 20,
  },
  subTitle: {
    fontSize: 18,
    // fontWeight: "bold",
  },
  deleteButton: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#ff4d4d",
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  deleteText: {
    color: "white",
    fontWeight: "bold",
  },
  dropdown: {
    marginBottom: 16,
  },
  requiredLabel: {
    fontSize: 14,
    color: "#d00", // red color for emphasis
  },
  radioContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  radioButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  radioCircle: {
    height: 15,
    width: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  radioSelected: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: "#000",
  },
  radioLabel: {
    fontSize: 15,
  },
});
